title: Barpak Gaon
email: budhram.gurung01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A beautiful village in the northern Gorkha, Nepal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://barpak.org"
twitter_username: coolbrg
github_username:  coolbrg
thumbnail_path: thumbnail.jpg

google_analytics: # your google analytics id

# Build settings
markdown: kramdown
